version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: frontend_test
    container_name: frontend_test
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
